apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.keepalived.authPassword }}
  password: {{ .Values.keepalived.authPassword | b64enc }}
  {{- else }}
  password: {{ printf "%s:%s" .Release.Name .Release.Namespace | sha256sum | trunc 8 | b64enc }}
  {{- end }}
